stages:
  - pre_build
  - build
  - docker
  - deploy

variables:
  APP_HOST: relayserver.incorum.org

include:
  - local: /.gitlab-ci/mvn.gitlab-ci.yml
  - local: /.gitlab-ci/Docker.gitlab-ci.yml

deploy_review:
  stage: deploy
  image: innoq/gitlabci-docker-compose:alpine
  variables:
    APP_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
    APP_DEPLOY_HOST: "${CI_ENVIRONMENT_SLUG}.${APP_HOST}"
    RELAY_UID: "${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}"
    RELAY_MONITORING_TOKEN: test
  script:
    - sh ./prepare-environment-docker-compose.sh > docker-compose.yml
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose pull
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG up -d --remove-orphans
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$APP_HOST
    on_stop: stop_review
  except:
    - master
  tags:
    - review
  # We don't need cache for deploy a review
  cache: {}

stop_review:
  stage: deploy
  image: innoq/gitlabci-docker-compose:alpine
  variables:
    GIT_STRATEGY: none
    APP_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  before_script:
    - apk add --no-cache git
    - git clone -n $CI_REPOSITORY_URL $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - git checkout $CI_COMMIT_SHA
  script:
    - sh ./prepare-environment-docker-compose.sh > docker-compose.yml
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG down
  except:
    - master
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - review
  # We don't need cache for stop a review
  cache: {}

deploy_staging:
  stage: deploy
  image: innoq/gitlabci-docker-compose:alpine
  variables:
    APP_IMAGE: "${CI_REGISTRY_IMAGE}:latest"
    APP_DEPLOY_HOST: "staging.${APP_HOST}"
    RELAY_UID: staging
  script:
    - sh ./prepare-environment-docker-compose.sh > docker-compose.yml
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose pull
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG up -d --remove-orphans
  environment:
    name: staging
    url: https://staging.$APP_HOST
  only:
    - master
  tags:
    - staging
  # We don't need cache for deploy staging
  cache: {}