apiVersion: v1
kind: Service
metadata:
  name: {{ include "drasyl.fullname" . }}
  labels:
    {{- include "drasyl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: drasyl
      protocol: UDP
      name: drasyl
  selector:
    {{- include "drasyl.selectorLabels" . | nindent 4 }}
