variables:
  APP_HOST: env.drasyl.org

.deploy-base-docker: &deploy-base-docker
  image: git.informatik.uni-hamburg.de:4567/sane/sane-build-images:docker-18.02-docker-compose-1.19-git-2.15.4
  script:
    - sh ./prepare-environment-docker-compose.sh > docker-compose.yml
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose pull
    - docker-compose --project-name ${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_ENVIRONMENT_SLUG} up -d --remove-orphans
  # We don't need cache for stop a environment
  cache: {}

.stop-base-docker: &stop-base-docker
  image: git.informatik.uni-hamburg.de:4567/sane/sane-build-images:docker-18.02-docker-compose-1.19-git-2.15.4
  before_script:
    - git clone -n $CI_REPOSITORY_URL $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - git checkout $CI_COMMIT_SHA || git checkout master
  script:
    - sh ./prepare-environment-docker-compose.sh > docker-compose.yml
    - docker-compose --project-name ${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_ENVIRONMENT_SLUG} down
  # We don't need cache for stop a environment
  cache: {}

.deploy-base-kubernetes: &deploy-base-kubernetes
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v0.17.2
  script:
    - sh ./prepare-environment-kubernetes.sh > kubernetes.yml
    - cat kubernetes.yml
    - kubectl apply -f kubernetes.yml
  # We don't need cache for stop a environment
  cache: {}

.stop-base-kubernetes: &stop-base-kubernetes
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v0.17.2
  variables:
    GIT_STRATEGY: none
  before_script:
    - git clone -n $CI_REPOSITORY_URL $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - git checkout $CI_COMMIT_SHA || git checkout master
  script:
    - sh ./prepare-environment-kubernetes.sh > kubernetes.yml
    - kubectl delete -f kubernetes.yml
  # We don't need cache for stop a environment
  cache: {}

review:
  <<: *deploy-base-kubernetes
  stage: review
  variables:
    JAVA_OPTS: "-Dio.netty.leakDetectionLevel=PARANOID"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$APP_HOST
    on_stop: stop_review
  except:
    - master
  tags:
    - kubernetes
    - review
  # We don't need cache for deploy a review
  cache: {}

stop_review:
  <<: *stop-base-kubernetes
  stage: cleanup
  except:
    - master
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - kubernetes
    - review
  # We don't need cache for stop a review
  cache: {}

staging:
  <<: *deploy-base-kubernetes
  stage: staging
  variables:
    DRASYL_PROOF_OF_WORK: 10724607
    DRASYL_PUBLIC_KEY: 03096ae3080a369829a44847d5af1f652bef3f9921e9e1bbad64970babe6d3c502
    # DRASYL_PRIVATE_KEY is defined securely in GitLab CI/CD Settings
    JAVA_OPTS: "-Dio.netty.leakDetectionLevel=PARANOID"
  environment:
    name: staging
    url: https://$CI_ENVIRONMENT_SLUG.$APP_HOST
  only:
    - master
  tags:
    - kubernetes
    - staging

stop_staging:
  <<: *stop-base-kubernetes
  stage: cleanup
  variables:
    GIT_STRATEGY: none
    DRASYL_PROOF_OF_WORK: 10724607
    DRASYL_PUBLIC_KEY: 03096ae3080a369829a44847d5af1f652bef3f9921e9e1bbad64970babe6d3c502
    # DRASYL_PRIVATE_KEY is defined securely in GitLab CI/CD Settings
  only:
    - master
  when: manual
  environment:
    name: staging
    action: stop
  tags:
    - kubernetes
    - staging

production:
  <<: *deploy-base-docker
  stage: production
  variables:
    APP_IMAGE: "${CI_REGISTRY_IMAGE}:latest"
    APP_DEPLOY_HOST: "production.${APP_HOST}"
    SENTRY_ENVIRONMENT: production
    DRASYL_PROOF_OF_WORK: 10992904
    DRASYL_PUBLIC_KEY: 025fff6f625f5dee816d9f8fe43895479aecfda187cb6a3330894a07e698bc5bd8
    # DRASYL_PRIVATE_KEY is defined securely in GitLab CI/CD Settings
  environment:
    name: production
    url: https://$APP_HOST
    on_stop: stop_production
  only:
    - master
  when: manual
  tags:
    - docker
    - production

stop_production:
  <<: *stop-base-docker
  stage: cleanup
  variables:
    GIT_STRATEGY: none
    APP_IMAGE: "${CI_REGISTRY_IMAGE}:latest"
    APP_DEPLOY_HOST: "production.${APP_HOST}"
    SENTRY_ENVIRONMENT: production
    DRASYL_PROOF_OF_WORK: 10992904
    DRASYL_PUBLIC_KEY: 025fff6f625f5dee816d9f8fe43895479aecfda187cb6a3330894a07e698bc5bd8
    # DRASYL_PRIVATE_KEY is defined securely in GitLab CI/CD Settings
  only:
    - master
  when: manual
  environment:
    name: production
    action: stop
  tags:
    - docker
    - production
