.docker: &docker
  stage: .post
  # Official docker image.
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-build-master:
  <<: *docker
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE" .
    # minimal test
    - docker run --rm "$CI_REGISTRY_IMAGE" --help
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  <<: *docker
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    # minimal test
    - docker run --rm "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --help
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master