image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

.maven-base: &maven-base
  before_script:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    paths:
      - "drasyl-*.zip"
  needs: []

maven-verify:
  <<: *maven-base
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar'
  except:
    - master
    - /^\d+\.\d+/

maven-deploy:
  <<: *maven-base
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install sonar:sonar'
    - 'mvn $MAVEN_CLI_OPTS clean deploy -DskipTests -Darguments=-DskipTests -P release'
  only:
    - master
    - /^\d+\.\d+/