image: drasyl/drasyl-build-images:jdk-11-maven-3.6.3-gpg-pinentry-tty

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

.maven-base: &maven-base
  before_script:
    - export GPG_TTY=$(tty)
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
    - for file in drasyl-*.zip; do sha256sum "$file" | awk '{print $1}' > "$file.sha256"; done
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    paths:
      - "drasyl-*.zip"
      - "drasyl-*.zip.sha256"
      - "drasyl-integration-tests/target/site/jacoco-aggregate/jacoco.xml"
  needs: []

maven-verify:
  <<: *maven-base
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify -Prelease,ossrh sonar:sonar'
  except:
    - master
    - /^v\d+\.\d+/

maven-deploy:
  <<: *maven-base
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -Prelease,ossrh clean package source:jar gpg:sign install:install deploy:deploy sonar:sonar'
  only:
    - master
    - /^v\d+\.\d+/
