visual-coverage:
  stage: visualize
  image: haynes/jacoco2cobertura:latest
  script:
    # all module add to args
    - 'python /opt/cover2cover.py drasyl-integration-tests/target/site/jacoco-aggregate/jacoco.xml
                drasyl-cli/src/main/java
                drasyl-core/src/main/java
                drasyl-plugin-groups-client/src/main/java
                drasyl-plugin-groups-manager/src/main/java
                > drasyl-integration-tests/target/site/coverage.xml'
    - 'python /opt/source2filename.py drasyl-integration-tests/target/site/coverage.xml'
  except:
    - master
    - /^v\d+\.\d+/
  needs: [ "maven-verify" ]
  dependencies:
    - maven-verify
  artifacts:
    reports:
      cobertura: drasyl-integration-tests/target/site/coverage.xml
