name: Build and Deploy Docs
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          curl -sI https://github.com/containous/structor/releases/latest | grep -Fi Location  | tr -d '\r' | sed "s/tag/download/g" | awk -F " " '{ print $2 "/structor_linux-amd64"}' | wget --output-document=$GOPATH/bin/structor -i -
          chmod +x $GOPATH/bin/structor
      - name: Build
        run: |
          cd docs/
          structor --owner="drasyl-overlay" --repo-name="drasyl" --dockerfile-url="https://raw.githubusercontent.com/drasyl-overlay/drasyl/master/docs/docs.Dockerfile" --menu.js-url="https://raw.githubusercontent.com/mmatur/structor-sample/master/structor-menu.js.gotmpl" --exp-branch=master --force-edit-url --debug
      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: docs/site
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Download Docs Artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact
          path: docs/site
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages