name: Build and Deploy Docs
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Build
        run: |
          cd docs/
          make docs
      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: docs/site
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Download Docs Artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact
          path: docs/site
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages